export let status: HTMLElement | null;
export let refreshBtn: HTMLElement | null;
export let historyList: HTMLElement | null;
export let setupGrid: HTMLElement | null;
export let tabButtons: HTMLElement[] = [];
export let tabPanels: HTMLElement[] = [];
export let bazelConfig: HTMLElement | null;
export let copyBazelConfigBtn: HTMLElement | null;
export let copyBazelConfigStatus: HTMLElement | null;
export let sinkConfig: HTMLElement | null;

export let summaryGrid: HTMLElement | null;
export let keywordList: HTMLElement | null;
export let timelineSummary: HTMLElement | null;
export let timelineChart: HTMLElement | null;
export let timelineDetail: HTMLElement | null;
export let timelineFilterButtons: HTMLElement[] = [];
export let timelineLimit: HTMLSelectElement | null;
export let hostJvmArgsList: HTMLElement | null;
export let jvmMetricsList: HTMLElement | null;
export let timingMetricsList: HTMLElement | null;
export let networkMetricsList: HTMLElement | null;
export let workerStatsList: HTMLElement | null;
export let findingsList: HTMLElement | null;
export let failedTargetsList: HTMLElement | null;
export let cacheOverviewList: HTMLElement | null;
export let cacheMissReasonsList: HTMLElement | null;
export let flakyTestsList: HTMLElement | null;
export let flakyAttemptsList: HTMLElement | null;
export let compileTopList: HTMLElement | null;
export let ioTopList: HTMLElement | null;
export let testExecWallTopList: HTMLElement | null;
export let artifactReferencesList: HTMLElement | null;
export let slowActionsList: HTMLElement | null;
export let slowTestsList: HTMLElement | null;
export let actionsList: HTMLElement | null;
export let runnerCountsList: HTMLElement | null;
export let timingBreakdownList: HTMLElement | null;

export function initDom() {
  status = document.getElementById("status");
  refreshBtn = document.getElementById("refresh-btn");
  historyList = document.getElementById("history-list");
  setupGrid = document.getElementById("setup-grid");
  tabButtons = Array.from(document.querySelectorAll("[data-tab]")) as HTMLElement[];
  tabPanels = Array.from(document.querySelectorAll("[data-tab-panel]")) as HTMLElement[];
  bazelConfig = document.getElementById("bazel-config");
  copyBazelConfigBtn = document.getElementById("copy-bazel-config-btn");
  copyBazelConfigStatus = document.getElementById("copy-bazel-config-status");
  sinkConfig = document.getElementById("sink-config");

  summaryGrid = document.getElementById("summary-grid");
  keywordList = document.getElementById("keyword-list");
  timelineSummary = document.getElementById("timeline-summary");
  timelineChart = document.getElementById("timeline-chart");
  timelineDetail = document.getElementById("timeline-detail");
  timelineFilterButtons = Array.from(
    document.querySelectorAll("[data-timeline-filter]"),
  ) as HTMLElement[];
  timelineLimit = document.getElementById("timeline-limit") as HTMLSelectElement | null;
  hostJvmArgsList = document.getElementById("host-jvm-args-list");
  jvmMetricsList = document.getElementById("jvm-metrics-list");
  timingMetricsList = document.getElementById("timing-metrics-list");
  networkMetricsList = document.getElementById("network-metrics-list");
  workerStatsList = document.getElementById("worker-stats-list");
  findingsList = document.getElementById("findings-list");
  failedTargetsList = document.getElementById("failed-targets-list");
  cacheOverviewList = document.getElementById("cache-overview-list");
  cacheMissReasonsList = document.getElementById("cache-miss-reasons-list");
  flakyTestsList = document.getElementById("flaky-tests-list");
  flakyAttemptsList = document.getElementById("flaky-attempts-list");
  compileTopList = document.getElementById("compile-top-list");
  ioTopList = document.getElementById("io-top-list");
  testExecWallTopList = document.getElementById("test-exec-wall-top-list");
  artifactReferencesList = document.getElementById("artifact-references-list");
  slowActionsList = document.getElementById("slow-actions-list");
  slowTestsList = document.getElementById("slow-tests-list");
  actionsList = document.getElementById("actions-list");
  runnerCountsList = document.getElementById("runner-counts-list");
  timingBreakdownList = document.getElementById("timing-breakdown-list");
}
