[package]
name = "bepless-grpc-ingest"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44", features = ["macros", "rt-multi-thread", "signal"] }
tonic = { version = "0.12", features = ["transport"] }
tonic-health = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
