[package]
name = "bepless-grpc-ingest"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.8"
aws-sdk-s3 = "1.92"
base64 = "0.22"
flate2 = "1.1"
prost = "0.13"
prost-types = "0.13"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.44", features = ["macros", "rt-multi-thread", "signal"] }
tokio-stream = "0.1"
tonic = { version = "0.12", features = ["transport"] }
tonic-health = "0.12"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[build-dependencies]
tonic-build = "0.12"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
