name = "bep-analyzer-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2026-04-20"
workers_dev = true

[build]
command = "cargo install -q --locked worker-build && worker-build --release"

[env.dev]
name = "bep-analyzer-worker-dev"

[env.production]
name = "bep-analyzer-worker"
